USE [master]
GO

/****** Object:  Database [BlenderPortfolio]    Script Date: 9/27/2020 3:11:44 PM ******/
CREATE DATABASE [BlenderPortfolio]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BlenderPortfolio', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BlenderPortfolio.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BlenderPortfolio_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BlenderPortfolio_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BlenderPortfolio].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BlenderPortfolio] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BlenderPortfolio] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BlenderPortfolio] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BlenderPortfolio] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BlenderPortfolio] SET ARITHABORT OFF 
GO

ALTER DATABASE [BlenderPortfolio] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BlenderPortfolio] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BlenderPortfolio] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BlenderPortfolio] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BlenderPortfolio] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BlenderPortfolio] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BlenderPortfolio] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BlenderPortfolio] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BlenderPortfolio] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BlenderPortfolio] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BlenderPortfolio] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BlenderPortfolio] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BlenderPortfolio] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BlenderPortfolio] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BlenderPortfolio] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BlenderPortfolio] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BlenderPortfolio] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BlenderPortfolio] SET RECOVERY FULL 
GO

ALTER DATABASE [BlenderPortfolio] SET  MULTI_USER 
GO

ALTER DATABASE [BlenderPortfolio] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BlenderPortfolio] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BlenderPortfolio] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BlenderPortfolio] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BlenderPortfolio] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BlenderPortfolio] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BlenderPortfolio] SET  READ_WRITE 
GO


